language: php

php:
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

install:
  - composer install

script: phpunit
notifications: { email: false }
